services:
  db:
    image: postgres:16
    container_name: wms-postgres
    environment:
      POSTGRES_USER: "1111"
      POSTGRES_PASSWORD: "1111"
      POSTGRES_DB: "warehouse"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U 1111 -d warehouse"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  db_data:
